### ISSUE TITLE
Example Project with Phoenix?

### ISSUE THREAD

**Issue by ghost** [zambal/marker#1]
Howdy. This looks really neat. I already see your description that it integrates well with Phoenix...do you have an example "Hello World" project that does this?

**Comment by zambal** [comment]
Thanks! I just started a simple Phoenix sample project at: [zambal/marker-phoenix-example](https://github.com/zambal/marker-phoenix-example). Hope that helps.

**Comment by ghost** [comment]
Sweet! I wasn't going to code today, but this has inspired me to go ahead and incorporate this since I'm starting fresh again with the UI side of things. I'll be sure to hit you up if I have any questions. :-O

**Comment by ghost** [comment]
Awesome. I've changed my home page to use Marker and it was pretty painless...of course it's a bare skeleton home page! The only hiccup was trying to figure out how to inline a `do` statement: 

```
a href: "/" do
  span class: "logo"
end
```

After looking at your code for [`def_element`](https://github.com/zambal/marker/blob/master/lib/marker/element.ex#L86):

```
%Marker.Element{tag: tag, attrs: attrs, content: content}
```

I realized that the macro generated just had some white-space issues, and I just needed to enclose the second param (`attrs`) in `[]`s:

```
a [href: "/"], do: span class: "logo"
```

Clean! I assume this is because Elixir only implies the brackets around the last statement? 

Anyway, initially this looks really exciting. I'm hoping that your component-ization works out as promising as it looks. I only need a very simple web app, but I need extensive use of **dynamically generated components**, similar to Angular. I also need to stay in the Elixir world because I am trying not to have to maintain logic in both js and Elixir for the time being.

So thanks for your hard work :muscle:

**Comment by zambal** [comment]
Thanks for the kind words, much appreciated! However, I'm not sure if I understand your issue with inline do statements. The idea is that it shouldn't matter how you call the element macros, as long as attributes are a `Keyword` literal. If I do this in a Elixir shell:

``` elixir
iex> use Marker.HTML
Marker.HTML
iex> el1 = a href: "/" do
...>   span class: "logo"
...>  end
{:safe, "<a href='/'><span class='logo'></span></a>"}
iex> el2 = a [href: "/"], do: span class: "logo"
{:safe, "<a href='/'><span class='logo'></span></a>"}
iex> el1 == el2
true
```

In other words, both notations should give exactly the same output.

Regarding components, if I understand you correctly, I don't think Marker components do what you hope they'll do. I have to admit that calling them components might be confusing, as components are also a concept in the world of single page web applications, where they are used for client side rendering. 

Marker components are only a tool for server side rendering. The result of calling a component is always a static string of HTML before send to the client. So it has nothing to do with Angular (or React, Vue.js, etc.) components.

However, I'm keeping an eye on ElixirScript, a project for compiling Elixir to Javascript. I think it could be quite interesting using Marker with ElixirScript to render HTML client side. But as Marker makes heavy use of macros, I don't think ElixirScript is ready yet for such integration.

**Comment by ghost** [comment]
Ah, just a misunderstanding:  It compiled to the same html fine, and I didn't mean to imply anything different. My initial problem was that I was not including the brackets around the `href` argument. So I had:

```
a href: "/", do: span class: "logo"
```

which doesn't work, because Elixir doesn't automagically add the brackets. 

Here is the fuller version that I then tried which DOES work, but has unnecessary brackets around the `do` statement:

```
a [href: "/"], [do: span class: "logo"]
```

This, as you are probably already aware, works as well. I am still a newb with Elixir (3 or 4 months now), and this is one of the syntactical aspects that still throws me about the language. 

As for the component-ization, even though I'm not a web/front end person (at all really), I understand that it can't be as dynamic as client-side rendering. But it looks to give me an easier method of generating components on the server side, as opposed to the template syntax that comes out of the box. Although, I've just learned that recently they've enabled [nested template structure](https://elixirforum.com/t/how-to-render-a-template-inside-a-web-templates-folder-subfolder/1404/4) in the conventions with the `pattern` option...maybe they've had it all along, but I couldn't find it in any documentation. 

But it looks like from your structure, I can simply create new files, wherever I want inside of the `web` folder so they are compiled per request, and then use those components...this is correct yes? 

Aside from this, I like avoiding the templates just for typing reasons. I may be a little dumb with some things, but I dislike typing `<% ... %>` all over the place, and the atom snippets that I'm using have `=` as the trigger for that particular snippet...which doesn't seem to work for me. But that's neither here nor there.

I'm going to keep using Marker for now, and if it doesn't do what I want it to do I'll let you know! :-O

**Comment by zambal** [comment]
Now I see. Sorry, I guess I interpreted both your questions wrong. You are indeed right that the first argument needs to be enclosed in brackets, becauses otherwise it would be impossible to know that the 'do' keyword is actually the second argument of the call. However, all the syntactic sugar around Keyword lists in function calls took a while too for me before it 'clicked' when first learning Elixir.

It might help to realize that in the end, it are all lists of tuples, so:

``` elixir
h1 do
 "Hello World"
end
```

is almost\* syntactic sugar for:

``` elixir
h1 do: "Hello World"
```

which is synctatic sugar for:

``` elixir
h1 [do: "Hello World"]
```

which is syntactic sugar for:

``` elixir
h1 [{:do, "Hello World"}]
```

and that the bracketless syntax is only allowed for the last argument in function calls

Regarding components, yes, you should be able to place new files anywhere in in the `web` folder and thanks to Phoenix's hot code reloading feature, templates/components will be automatically recompiled when the source code file is saved and requested again.

BTW, disliking the `<% ... %>` syntax and not really being a front end person too were reasons for me to start developing Marker :)
- `do ... end` blocks are a special case as the content within such block is wrapped in a `__block__` structure to allow multi line expressions (see http://elixir-lang.org/docs/stable/elixir/Kernel.SpecialForms.html#__block__/1)

**Comment by ghost** [comment]
Ah, nice syntactic sugar example, and it really setup the link to the excellent `__block__` documentation - the `do:`, `do...end` syntax has really been a thorn in my side so far. I am just used to OOP languages where it's just one version, and it "simply" declares a scope that gets compiled/interpreted. This is at the heart of why my [nested `with` statements wouldn't compile](https://elixirforum.com/t/case-pyramid-of-doom-nested-with-nested-happy-path/1407/6?u=ibgib). But it's cool...I'll get there eventually. There is so much else for me to focus on though in my business domain logic that it's difficult sometimes to decide when to deep dive and when to keep chugging. 

But I digress...speaking of which, do you have a slack team or a gitter account? I like these issues for more specific questions, but I do tend to ramble.

Ah, and I had another question. Is there any chance of snippets or anything to incorporate some of the conveniences in Phoenix regarding csrf tokens? I'm currently diving into the generated Phoenix.HTML output and mimicking it, but I would think it would be a pretty typical use case.

**Comment by zambal** [comment]
I love to continue discussing, but I think that we'd better continue elsewhere too, so I can keep the issue tracker a bit clean. However, I haven't used slack or gitter, but I see I can just login into gitter with my github account, so that's fine by me. I'll send you a ping and later today reply to this message on gitter.
